name: Spoolman
version: '0.1.2'
slug: spoolman
description: 3D printing filament spool manager
boot: auto
auto_update: false
url: https://github.com/Hiosdra/hassio-addons
arch: 
  - aarch64
  - amd64
options: {}
schema: {}
image: hiosdra/spoolman-addon
ports:
  8000/tcp: 7912
webui: http://[HOST]:[PORT:8000]
map: 
  - data:rw